[2023-11-16T20:01:35.177+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.tsk_load_to_s3 scheduled__2023-11-15T00:00:00+00:00 [queued]>
[2023-11-16T20:01:35.184+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.tsk_load_to_s3 scheduled__2023-11-15T00:00:00+00:00 [queued]>
[2023-11-16T20:01:35.185+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 3
[2023-11-16T20:01:35.201+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): tsk_load_to_s3> on 2023-11-15 00:00:00+00:00
[2023-11-16T20:01:35.205+0000] {standard_task_runner.py:57} INFO - Started process 4351 to run task
[2023-11-16T20:01:35.209+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag', 'tsk_load_to_s3', 'scheduled__2023-11-15T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp8607aldw']
[2023-11-16T20:01:35.210+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask tsk_load_to_s3
[2023-11-16T20:01:35.249+0000] {task_command.py:416} INFO - Running <TaskInstance: weather_dag.tsk_load_to_s3 scheduled__2023-11-15T00:00:00+00:00 [running]> on host ip-172-31-10-167.us-west-1.compute.internal
[2023-11-16T20:01:35.309+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='tsk_load_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-11-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-15T00:00:00+00:00'
[2023-11-16T20:01:35.310+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-16T20:01:35.311+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'aws s3 mv /home/ubuntu/current_weather_data_16112023195719.csv s3://weatherapi-multiple-citites']
[2023-11-16T20:01:35.317+0000] {subprocess.py:86} INFO - Output:
[2023-11-16T20:01:36.215+0000] {subprocess.py:93} INFO - Completed 1.2 KiB/1.2 KiB (3.0 KiB/s) with 1 file(s) remainingmove failed: ../../home/ubuntu/current_weather_data_16112023195719.csv to s3://weatherapi-multiple-citites/current_weather_data_16112023195719.csv An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
[2023-11-16T20:01:36.288+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-16T20:01:36.296+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/airflow_slack_venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-16T20:01:36.298+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=weather_dag, task_id=tsk_load_to_s3, execution_date=20231115T000000, start_date=20231116T200135, end_date=20231116T200136
[2023-11-16T20:01:36.317+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 13 for task tsk_load_to_s3 (Bash command failed. The command returned a non-zero exit code 1.; 4351)
[2023-11-16T20:01:36.344+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-16T20:01:36.357+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
